In [4]:
import pandas as pd

In [5]:
df_17 = pd.read_csv('17.csv')

In [17]:
df_17

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,VALOR DECLARADO,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,4.00,6,PENDIENTE EN DESTINO,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,5575144.50,6,ENTREGADO,014676,MVARONE,NaN,NaN,NaN,014676,NaN
2,1089337521,01/02/2023,000502483732R,82970536.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2495304.00,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:29 PM,NaN,NaN,015632,NaN
3,1089337522,01/02/2023,000502483733R,82970537.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,15692418.72,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:24 PM,NaN,NaN,015632,NaN
4,1089337523,01/02/2023,000502483734R,82970538.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2179502.60,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:20 PM,NaN,NaN,015632,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8778,1089775292,17/02/2023,0082977669,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8779,1089775513,17/02/2023,0082977636,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8780,1089775540,17/02/2023,0082977675,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,cyedro,NaN,NaN,NaN,NaN,NaN
8781,1089775762,17/02/2023,0082978028,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,sarredondo,NaN,NaN,NaN,NaN,NaN
8782,1089775771,17/02/2023,0082977536,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN

In [18]:
# Mostrar las 5 primeras filas
df_17.head()

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,VALOR DECLARADO,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,4.00,6,PENDIENTE EN DESTINO,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,5575144.50,6,ENTREGADO,014676,MVARONE,NaN,NaN,NaN,014676,NaN
2,1089337521,01/02/2023,000502483732R,82970536.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2495304.00,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:29 PM,NaN,NaN,015632,NaN
3,1089337522,01/02/2023,000502483733R,82970537.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,15692418.72,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:24 PM,NaN,NaN,015632,NaN
4,1089337523,01/02/2023,000502483734R,82970538.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2179502.60,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:20 PM,NaN,NaN,015632,NaN

In [19]:
# Mostrar las 5 ultimas filas
df_17.tail()

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,VALOR DECLARADO,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA
8778,1089775292,17/02/2023,0082977669,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.0,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8779,1089775513,17/02/2023,0082977636,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.0,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8780,1089775540,17/02/2023,0082977675,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.0,47,PDTE.ORIGEN,NaN,cyedro,NaN,NaN,NaN,NaN,NaN
8781,1089775762,17/02/2023,0082978028,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.0,47,PDTE.ORIGEN,NaN,sarredondo,NaN,NaN,NaN,NaN,NaN
8782,1089775771,17/02/2023,0082977536,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.0,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN

In [87]:
# Mostrar N filas
pd.set_option('display.max_rows', 10)
df_17

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,VALOR DECLARADO,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,4.00,6,PENDIENTE EN DESTINO,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,5575144.50,6,ENTREGADO,014676,MVARONE,NaN,NaN,NaN,014676,NaN
2,1089337521,01/02/2023,000502483732R,82970536.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2495304.00,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:29 PM,NaN,NaN,015632,NaN
3,1089337522,01/02/2023,000502483733R,82970537.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,15692418.72,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:24 PM,NaN,NaN,015632,NaN
4,1089337523,01/02/2023,000502483734R,82970538.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2179502.60,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:20 PM,NaN,NaN,015632,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8778,1089775292,17/02/2023,0082977669,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8779,1089775513,17/02/2023,0082977636,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8780,1089775540,17/02/2023,0082977675,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,cyedro,NaN,NaN,NaN,NaN,NaN
8781,1089775762,17/02/2023,0082978028,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,sarredondo,NaN,NaN,NaN,NaN,NaN
8782,1089775771,17/02/2023,0082977536,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN

In [22]:
# Accediendo al atributo shape
df_17.shape # Numero de filas y de columnas

(8783, 42)

In [23]:
# Acceso atributo index
df_17.index

RangeIndex(start=0, stop=8783, step=1)

In [24]:
# Acceso al atributo columns
df_17.columns

Index(['NENVIO', 'FECHA', 'REFERENCIA', 'REF_ADICIONAL', 'OBSER1', 'OBSER2',
       'CODREMI', 'CLIENTE', 'ORIGEN', 'DESTINO', 'CP_ORI', 'CP_DES',
       'F_RECOGIDA', 'F_PACTADA', 'HORA_EA_DESDE', 'HORA_EA_HASTA',
       'F_CIERRE_SALIDA', 'FECHA LLEGADA', 'FECHA ASIGNACION', 'F_ENTREGA',
       'F_DEVOLUCION', 'USUARIO_B', 'NOMBRE_DEST', 'DOMICILIO_DES',
       'LOCALIDAD_DES', 'PEDIDO_CERRADO_CC', 'BULTOS', 'PALETS', 'KILOS',
       'KILOS AFORADOS', 'VOLUMEN', 'GESTION COBRANZAS', 'VALOR DECLARADO',
       'KEYTSV', 'SITUACION', 'CENTRO_COSTO', 'USUARIO_G', 'FEC_MOBILE',
       'FEC_MOBILE_2115', 'FEC_MOBILE_CDS', 'CENTRO_COSTO_1', 'UCA'],
      dtype='object')

In [35]:
# Tipo de dato de cada columna
df_17.dtypes

NENVIO               int64
FECHA               object
REFERENCIA          object
REF_ADICIONAL      float64
OBSER1              object
                    ...
FEC_MOBILE          object
FEC_MOBILE_2115     object
FEC_MOBILE_CDS      object
CENTRO_COSTO_1      object
UCA                 object
Length: 42, dtype: object

In [36]:
# Obtener informacion sobre el DataFrame
df_17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8783 entries, 0 to 8782
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NENVIO             8783 non-null   int64
 1   FECHA              8783 non-null   object
 2   REFERENCIA         8783 non-null   object
 3   REF_ADICIONAL      6933 non-null   float64
 4   OBSER1             969 non-null    object
 5   OBSER2             223 non-null    object
 6   CODREMI            8783 non-null   int64
 7   CLIENTE            8783 non-null   object
 8   ORIGEN             8783 non-null   object
 9   DESTINO            8783 non-null   object
 10  CP_ORI             8783 non-null   int64
 11  CP_DES             8783 non-null   int64
 12  F_RECOGIDA         8783 non-null   object
 13  F_PACTADA          4323 non-null   object
 14  HORA_EA_DESDE      16 non-null     object
 15  HORA_EA_HASTA      16 non-null     object
 16  F_CIERRE_SALIDA    7610 non-null   object
 17  FECHA LLEGADA      7189 non-null   object
 18  FECHA ASIGNACION   6992 non-null   object
 19  F_ENTREGA          5750 non-null   object
 20  F_DEVOLUCION       14 non-null     object
 21  USUARIO_B          546 non-null    object
 22  NOMBRE_DEST        8783 non-null   object
 23  DOMICILIO_DES      8781 non-null   object
 24  LOCALIDAD_DES      8783 non-null   object
 25  PEDIDO_CERRADO_CC  5976 non-null   object
 26  BULTOS             8783 non-null   int64
 27  PALETS             8783 non-null   int64
 28  KILOS              8783 non-null   float64
 29  KILOS AFORADOS     8783 non-null   float64
 30  VOLUMEN            8783 non-null   float64
 31  GESTION COBRANZAS  8783 non-null   float64
 32  VALOR DECLARADO    8783 non-null   float64
 33  KEYTSV             8783 non-null   int64
 34  SITUACION          8783 non-null   object
 35  CENTRO_COSTO       8151 non-null   object
 36  USUARIO_G          8783 non-null   object
 37  FEC_MOBILE         3783 non-null   object
 38  FEC_MOBILE_2115    608 non-null    object
 39  FEC_MOBILE_CDS     9 non-null      object
 40  CENTRO_COSTO_1     8151 non-null   object
 41  UCA                5711 non-null   object
dtypes: float64(6), int64(7), object(29)
memory usage: 2.8+ MB

In [37]:
# Obtener valores estadisticos del DataFrame
df_17.describe()

,NENVIO,REF_ADICIONAL,CODREMI,CP_ORI,CP_DES,BULTOS,PALETS,KILOS,KILOS AFORADOS,VOLUMEN,GESTION COBRANZAS,VALOR DECLARADO,KEYTSV
count,8.783000e+03,6.933000e+03,8.783000e+03,8783.000000,8783.000000,8783.000000,8783.000000,8783.000000,8783.000000,8783.000000,8.783000e+03,8.783000e+03,8783.000000
mean,1.089590e+09,8.291993e+07,1.576161e+08,1680.176250,3190.862234,3.491290,0.035182,64.336279,219.470290,0.537849,8.456797e+04,1.981200e+06,14.296368
std,1.035016e+05,1.993541e+06,2.867705e+08,582.682448,2170.771753,6.274459,0.864553,825.897154,1007.867919,1.894093,6.749783e+05,7.429991e+06,15.397621
min,1.089281e+09,1.328080e+05,4.008031e+06,1001.000000,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
25%,1.089494e+09,8.297290e+07,6.000940e+07,1614.000000,1605.000000,1.000000,0.000000,1.000000,3.850000,0.010000,0.000000e+00,1.000000e+00,6.000000
50%,1.089587e+09,8.297450e+07,6.000940e+07,1614.000000,1878.000000,1.000000,0.000000,4.000000,31.150000,0.042000,0.000000e+00,1.067816e+05,6.000000
75%,1.089675e+09,8.297626e+07,6.000940e+07,1614.000000,5004.000000,3.000000,0.000000,19.000000,93.450000,0.180000,0.000000e+00,7.330512e+05,14.000000
max,1.089776e+09,8.297804e+07,1.000000e+09,9420.000000,9420.000000,218.000000,50.000000,56556.800000,56556.800000,40.368000,2.508724e+07,1.497271e+08,99.000000

In [ ]:
# Funciones

In [39]:
# Obtener el tamaño del DataFrame (filas)
len(df_17)

8783

In [41]:
# Obtener el maximo index
max(df_17.index)

8782

In [42]:
# obtener el minimo index
min(df_17.index)

0

In [43]:
# obtener el tipo de dato del dataframe
type(df_17)

pandas.core.frame.DataFrame

In [44]:
# redondear los valores del dataframe
round(df_17,2)

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,VALOR DECLARADO,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,4.00,6,PENDIENTE EN DESTINO,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,5575144.50,6,ENTREGADO,014676,MVARONE,NaN,NaN,NaN,014676,NaN
2,1089337521,01/02/2023,000502483732R,82970536.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2495304.00,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:29 PM,NaN,NaN,015632,NaN
3,1089337522,01/02/2023,000502483733R,82970537.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,15692418.72,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:24 PM,NaN,NaN,015632,NaN
4,1089337523,01/02/2023,000502483734R,82970538.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,2179502.60,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:20 PM,NaN,NaN,015632,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8778,1089775292,17/02/2023,0082977669,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8779,1089775513,17/02/2023,0082977636,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN
8780,1089775540,17/02/2023,0082977675,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,cyedro,NaN,NaN,NaN,NaN,NaN
8781,1089775762,17/02/2023,0082978028,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,sarredondo,NaN,NaN,NaN,NaN,NaN
8782,1089775771,17/02/2023,0082977536,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,1.00,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN

In [50]:
# seleccionar una columna de un dataframe
df_17['SITUACION']

0       PENDIENTE EN DESTINO
1                  ENTREGADO
2                  ENTREGADO
3                  ENTREGADO
4                  ENTREGADO
                ...
8778             PDTE.ORIGEN
8779             PDTE.ORIGEN
8780             PDTE.ORIGEN
8781             PDTE.ORIGEN
8782             PDTE.ORIGEN
Name: SITUACION, Length: 8783, dtype: object

In [51]:
# Filtrar por valor de la columna
df_17['SITUACION'] == 'PDTE.ORIGEN'

0       False
1       False
2       False
3       False
4       False
        ...
8778     True
8779     True
8780     True
8781     True
8782     True
Name: SITUACION, Length: 8783, dtype: bool

In [80]:
# revisar el tipo de dato de una columna
type(df_17['SITUACION'] == 'PDTE.ORIGEN')

pandas.core.series.Series

In [85]:
# series: atributos y metodos
df_17['SITUACION'].index
df_17['SITUACION'].head()

0    PENDIENTE EN DESTINO
1               ENTREGADO
2               ENTREGADO
3               ENTREGADO
4               ENTREGADO
Name: SITUACION, dtype: object

In [90]:
# Seleccionar una columna con .
df_17.SITUACION

0       PENDIENTE EN DESTINO
1                  ENTREGADO
2                  ENTREGADO
3                  ENTREGADO
4                  ENTREGADO
                ...
8778             PDTE.ORIGEN
8779             PDTE.ORIGEN
8780             PDTE.ORIGEN
8781             PDTE.ORIGEN
8782             PDTE.ORIGEN
Name: SITUACION, Length: 8783, dtype: object

In [96]:
df_origen = df_17['SITUACION'] == 'PDTE.ORIGEN' # Guardamos los valores PDTE.ORIGEN de la columna SITUACION en otro dataframe
filtered_df = df_17[df_origen] # filtramos

In [97]:
filtered_df.shape

(745, 42)

In [102]:
 # Seleccionar dos o mas columnas
filtered_df[['NENVIO','FECHA','DESTINO']]

          NENVIO       FECHA                      DESTINO
215   1089428919  01/02/2023                      ROSARIO
383   1089429294  01/02/2023       WH MALVINAS ARGENTINAS
609   1089436347  01/02/2023       WH MALVINAS ARGENTINAS
619   1089438172  01/02/2023       WH MALVINAS ARGENTINAS
766   1089451953  02/02/2023  AVELLANEDA - C DISTRIBUCIÓN
...          ...         ...                          ...
8778  1089775292  17/02/2023  AVELLANEDA - C DISTRIBUCIÓN
8779  1089775513  17/02/2023  AVELLANEDA - C DISTRIBUCIÓN
8780  1089775540  17/02/2023  AVELLANEDA - C DISTRIBUCIÓN
8781  1089775762  17/02/2023  AVELLANEDA - C DISTRIBUCIÓN
8782  1089775771  17/02/2023  AVELLANEDA - C DISTRIBUCIÓN

[745 rows x 3 columns]

In [103]:
# revisar el tipo de data de la seleccion
type(filtered_df[['NENVIO','FECHA','DESTINO']])

pandas.core.frame.DataFrame

In [7]:
# Agregar una columna al dataframe
df_17.head()
df_17['TOTAL'] = 0
df_17

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA,TOTAL
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,6,PENDIENTE EN DESTINO,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN,0
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,6,ENTREGADO,014676,MVARONE,NaN,NaN,NaN,014676,NaN,0
2,1089337521,01/02/2023,000502483732R,82970536.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:29 PM,NaN,NaN,015632,NaN,0
3,1089337522,01/02/2023,000502483733R,82970537.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:24 PM,NaN,NaN,015632,NaN,0
4,1089337523,01/02/2023,000502483734R,82970538.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:20 PM,NaN,NaN,015632,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8778,1089775292,17/02/2023,0082977669,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN,0
8779,1089775513,17/02/2023,0082977636,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN,0
8780,1089775540,17/02/2023,0082977675,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,47,PDTE.ORIGEN,NaN,cyedro,NaN,NaN,NaN,NaN,NaN,0
8781,1089775762,17/02/2023,0082978028,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,47,PDTE.ORIGEN,NaN,sarredondo,NaN,NaN,NaN,NaN,NaN,0
8782,1089775771,17/02/2023,0082977536,NaN,NaN,NaN,60009400,ROFINA S.A.I.C.F.,AVELLANEDA - C DISTRIBUCIÓN,AVELLANEDA - C DISTRIBUCIÓN,...,47,PDTE.ORIGEN,NaN,lmaidana,NaN,NaN,NaN,NaN,NaN,0

In [11]:
# Agregar una columna con array
# importar numpy
import numpy as np

In [12]:
# crear un array de 8783 elementos
total = np.arange(0,8783)

In [13]:
# tamaño del array
len(total)

8783

In [14]:
# agregar columna con un array
df_17['TOTAL'] = total
df_17.head()

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,KEYTSV,SITUACION,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA,TOTAL
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,6,PENDIENTE EN DESTINO,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN,0
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,6,ENTREGADO,014676,MVARONE,NaN,NaN,NaN,014676,NaN,1
2,1089337521,01/02/2023,000502483732R,82970536.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:29 PM,NaN,NaN,015632,NaN,2
3,1089337522,01/02/2023,000502483733R,82970537.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:24 PM,NaN,NaN,015632,NaN,3
4,1089337523,01/02/2023,000502483734R,82970538.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,14,ENTREGADO,015632,FDIAZ,01/02/2023 12:10:20 PM,NaN,NaN,015632,NaN,4

In [34]:
 # crear valores aleatorios entre 1 y 100
total_random = np.random.randint(1,100,size=8783)
total_random2 = np.random.randint(1,100,size=8783)
df_17['TOTAL'] = total_random
df_17['TOTAL2'] = total_random2
df_17.head(2)

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,CENTRO_COSTO,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA,TOTAL,TOTAL2,TOTAL_FINAL
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,028142,NPERAZZO,NaN,NaN,NaN,028142,NaN,95,19,14.0
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,014676,MVARONE,NaN,NaN,NaN,014676,NaN,49,90,18.0

In [17]:
# crear valores decimales aleatorios

np.random.uniform(1,100, size=8783)

array([83.82806699, 84.90770011,  4.8659391 , ..., 84.4407412 ,
       86.17346784, 79.21726881])

In [20]:
# selecciona una columna y calcula la suma total
df_17['TOTAL'].sum()

441334

In [22]:
# contar cantidad de elementos
df_17['TOTAL'].count()

8783

In [23]:
# promedio de todos los elementos
df_17['TOTAL'].mean()

50.24866218831834

In [37]:
# calculamos la suma de una fila

df_17['TOTAL_FINAL'] = df_17['TOTAL'] + df_17['TOTAL2']

In [40]:
# calcular el promedio y asignarselo a una nueva columna

df_17['PROMEDIO'] = (df_17['TOTAL'] + df_17['TOTAL2'])/2
df_17.head(2)
df_17.round(2).head(2)

,NENVIO,FECHA,REFERENCIA,REF_ADICIONAL,OBSER1,OBSER2,CODREMI,CLIENTE,ORIGEN,DESTINO,...,USUARIO_G,FEC_MOBILE,FEC_MOBILE_2115,FEC_MOBILE_CDS,CENTRO_COSTO_1,UCA,TOTAL,TOTAL2,TOTAL_FINAL,PROMEDIO
0,1089280830,02/02/2023,000502482638R,82969368.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,NPERAZZO,NaN,NaN,NaN,028142,NaN,95,19,114,57.0
1,1089304773,06/02/2023,000502483023R,82969763.0,NaN,NaN,60009400,ROFINA S.A.I.C.F.,WH MALVINAS ARGENTINAS,WH MALVINAS ARGENTINAS,...,MVARONE,NaN,NaN,NaN,014676,NaN,49,90,139,69.5

In [43]:
# contar los elementos de cualquier columna con mismo value

df_origen = df_17['SITUACION'] == 'PDTE.ORIGEN'
filtered_df = df_17[df_origen]
filtered_df['DESTINO'].value_counts()

AVELLANEDA - C DISTRIBUCIÓN    154
WH MALVINAS ARGENTINAS          88
CORDOBA                         64
ROSARIO                         63
BENAVIDEZ - C DISTRIBUCION      59
MENDOZA                         52
MAR DEL PLATA                   45
SANTA FE                        39
TANDIL                          36
CORRIENTES                      34
GUALEGUAYCHU                    30
SAN JUAN                        28
TUCUMAN                         12
FLORIDA (LOG INVERSA ZN)         5
LA RIOJA                         4
VILLA MARIA                      4
POSADAS                          4
SALTA                            4
JUJUY                            3
RESISTENCIA                      2
BAHIA BLANCA                     2
COMODORO RIVADAVIA               2
SAN LUIS                         2
JUNIN                            1
CONCORDIA                        1
CDS USHUAIA                      1
FORMOSA                          1
OLIVOS                           1
PARANA                           1
NEUQUEN                          1
RECONQUISTA                      1
BARILOCHE                        1
Name: DESTINO, dtype: int64

In [45]:
# contar los elementos de cualquier columna con mismo value y mostrar el porcentaje
filtered_df['DESTINO'].value_counts(normalize=True)

AVELLANEDA - C DISTRIBUCIÓN    0.206711
WH MALVINAS ARGENTINAS         0.118121
CORDOBA                        0.085906
ROSARIO                        0.084564
BENAVIDEZ - C DISTRIBUCION     0.079195
MENDOZA                        0.069799
MAR DEL PLATA                  0.060403
SANTA FE                       0.052349
TANDIL                         0.048322
CORRIENTES                     0.045638
GUALEGUAYCHU                   0.040268
SAN JUAN                       0.037584
TUCUMAN                        0.016107
FLORIDA (LOG INVERSA ZN)       0.006711
LA RIOJA                       0.005369
VILLA MARIA                    0.005369
POSADAS                        0.005369
SALTA                          0.005369
JUJUY                          0.004027
RESISTENCIA                    0.002685
BAHIA BLANCA                   0.002685
COMODORO RIVADAVIA             0.002685
SAN LUIS                       0.002685
JUNIN                          0.001342
CONCORDIA                      0.001342
CDS USHUAIA                    0.001342
FORMOSA                        0.001342
OLIVOS                         0.001342
PARANA                         0.001342
NEUQUEN                        0.001342
RECONQUISTA                    0.001342
BARILOCHE                      0.001342
Name: DESTINO, dtype: float64

In [ ]:
# ordenar por columna
df_17.sort_values('TOTAL')

In [ ]:
# ordenar descendiente por columna
df_17.sort_values('TOTAL',ascending=False)

In [ ]:
# ordenar descendiente por multiples columnas
df_17.sort_values(['TOTAL', 'TOTAL2'],ascending=False)

In [ ]:
# ordenar descendiente por multiples columnas y actualizar el dataframe
df_17.sort_values(['TOTAL', 'TOTAL2'],ascending=False, inplace=True)

In [ ]:
# ordenar descendiente con una funcion key
df_17.sort_values('TOTAL',ascending=True,key= lambda col:col.str.lower())